import { Track } from "../types/music-types";
import {
  ShadesOfGreenImage,
  DaylightImage,
  WolvesImage,
  MementoImage,
  FetishImage,
  DMsImage,
  LastChanceImage,
  FeelingThisImage,
  MyOwnWorstEnemyImage,
  HeavyImage,
  DungeonImage,
  CompetitionMixImage,
  BoysOfSummerImage,
  PumpkinSpiceMixImage,
  ChillaxMixImage,
  ClocksImage,
  LostAtSeaImage,
  HandsOfFoolsImage,
  SonanceImage,
} from "../public/album_artwork/index";

// TODO: Move this to a DB and file storage for images. Also remove some tracks and add newer ones.
export const trackList: Track[] = [
  {
    title: "Puzzle Pieces",
    link: "https://open.spotify.com/artist/7ep0M30TYlHUVnJsDwiLGe?si=7pgd7m8ERMyG1zImlQ7cTA",
    artworkSource: ShadesOfGreenImage,
    scURL: "https://soundcloud.com/tfar/puzzle-pieces",
  },
  {
    title: "Fly Away",
    link: "https://open.spotify.com/artist/7ep0M30TYlHUVnJsDwiLGe?si=7pgd7m8ERMyG1zImlQ7cTA",
    artworkSource: ShadesOfGreenImage,
    scURL: "https://soundcloud.com/tfar/fly-away",
  },
  {
    title: "Dawn",
    link: "https://open.spotify.com/artist/7ep0M30TYlHUVnJsDwiLGe?si=7pgd7m8ERMyG1zImlQ7cTA",
    artworkSource: ShadesOfGreenImage,
    scURL: "https://soundcloud.com/tfar/dawn",
  },
  {
    title: "Daylight",
    link: "https://soundcloud.com/tfar/daylight",
    artworkSource: DaylightImage,
    scURL: "https://soundcloud.com/tfar/daylight",
  },
  {
    title: "Wolves (Remix)",
    link: "https://soundcloud.com/tfar/selena-gomez-x-marshmello-wolves-nerves-remix",
    artworkSource: WolvesImage,
    scURL: "https://soundcloud.com/tfar/selena-gomez-x-marshmello-wolves-nerves-remix",
  },
  {
    title: "Memento",
    link: "https://soundcloud.com/tfar/memento",
    artworkSource: MementoImage,
    scURL: "https://soundcloud.com/tfar/memento",
  },
  {
    title: "Fetish (Remix)",
    link: "https://soundcloud.com/tfar/selena-gomez-fetish-nerves-remix",
    artworkSource: FetishImage,
    scURL: "https://soundcloud.com/tfar/selena-gomez-fetish-nerves-remix",
  },
  {
    title: "DMs (#SELFIE Pt. II)",
    link: "https://soundcloud.com/tfar/dms-selfie-pt-ii",
    artworkSource: DMsImage,
    scURL: "https://soundcloud.com/tfar/dms-selfie-pt-ii",
  },
  {
    title: "Kaskade x T. Swift Mashup",
    link: "https://soundcloud.com/nerves_music/i-knew-you-were-trouble-last-chance-taylor-swift-x-kaskade-mashup",
    artworkSource: LastChanceImage,
    scURL: "https://soundcloud.com/nerves_music/i-knew-you-were-trouble-last-chance-taylor-swift-x-kaskade-mashup",
  },
  {
    title: "Feeling This (Remix)",
    link: "https://soundcloud.com/tfar/feeling-this-intro",
    artworkSource: FeelingThisImage,
    scURL: "https://soundcloud.com/tfar/feeling-this-intro",
  },
  {
    title: "My Own Worst Enemy (Remix)",
    link: "https://soundcloud.com/tfar/lit-my-own-worst-enemy-nerves-remix-1",
    artworkSource: MyOwnWorstEnemyImage,
    scURL: "https://soundcloud.com/tfar/lit-my-own-worst-enemy-nerves-remix-1",
  },
  {
    title: "Heavy (Remix)",
    link: "https://soundcloud.com/nerves_music/linkin-park-ft-kiiara-heavy-frt-strs-remix",
    artworkSource: HeavyImage,
    scURL: "https://soundcloud.com/nerves_music/linkin-park-ft-kiiara-heavy-frt-strs-remix",
  },
  {
    title: "Welcome to the Dungeon",
    link: "https://soundcloud.com/nerves_music/welcome-to-the-dungeon-mini-mix",
    artworkSource: DungeonImage,
    scURL: "https://soundcloud.com/nerves_music/welcome-to-the-dungeon-mini-mix",
  },
  {
    title: "2017 Competition Mix",
    link: "https://soundcloud.com/nerves_music/2017-competition-mix",
    artworkSource: CompetitionMixImage,
    scURL: "https://soundcloud.com/nerves_music/2017-competition-mix",
  },
  {
    title: "Boys of Summer (Remix)",
    link: "https://soundcloud.com/tfar/don-henley-x-bell-x1-the-boys-of-summer-tfar-remix",
    artworkSource: BoysOfSummerImage,
    scURL: "https://soundcloud.com/tfar/don-henley-x-bell-x1-the-boys-of-summer-tfar-remix",
  },
  {
    title: "Fall '16 Pumpkin Spice Mix",
    link: "https://soundcloud.com/tfar/fall-2016-pumpkin-spice-mix",
    artworkSource: PumpkinSpiceMixImage,
    scURL: "https://soundcloud.com/tfar/fall-2016-pumpkin-spice-mix",
  },
  {
    title: "Summer '16 Chillax Mix",
    link: "https://soundcloud.com/tfar/summer-2016-chillax-mix",
    artworkSource: ChillaxMixImage,
    scURL: "https://soundcloud.com/tfar/summer-2016-chillax-mix",
  },
  {
    title: "Clocks (Remix)",
    link: "https://soundcloud.com/tfar/clocks-coldplay-t-far-house-remix",
    artworkSource: ClocksImage,
    scURL: "https://soundcloud.com/tfar/clocks-coldplay-t-far-house-remix",
  },
  {
    title: "The Sun",
    link: "https://struckred.bandcamp.com/album/hands-of-fools-ep",
    artworkSource: HandsOfFoolsImage,
    scURL: "https://soundcloud.com/tfar/struck-red-the-sun",
  },
  {
    title: "Hands of Fools",
    link: "https://struckred.bandcamp.com/album/hands-of-fools-ep",
    artworkSource: HandsOfFoolsImage,
    scURL: "https://soundcloud.com/tfar/struck-red-hands-of-fools",
  },
  {
    title: "Damaging",
    link: "https://struckred.bandcamp.com/album/lost-at-sea-ep",
    artworkSource: LostAtSeaImage,
    scURL: "https://soundcloud.com/tfar/struck-red-damaging",
  },
  {
    title: "Lost at Sea",
    link: "https://struckred.bandcamp.com/album/lost-at-sea-ep",
    artworkSource: LostAtSeaImage,
    scURL: "https://soundcloud.com/tfar/struck-red-lost-at-sea",
  },
  {
    title: "She Was Mine (Cover)",
    link: "https://sonanceband.bandcamp.com",
    artworkSource: SonanceImage,
    scURL: "https://soundcloud.com/tfar/she-was-mine-cover",
  },
  {
    title: "Sweater Weather (Cover)",
    link: "https://sonanceband.bandcamp.com",
    artworkSource: SonanceImage,
    scURL: "https://soundcloud.com/tfar/sweater-weather-cover",
  },
];
