import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/music.module.scss";
import { Divider, Grid, Typography } from "@mui/material";
import { trackList, getLinkType } from "../utils/music";
import SongCard from "../components/SongCard/SongCard";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Music - Trevor Farthing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant="body1">{"Some tracks I've produced or recorded on."}</Typography>
        <Divider variant="fullWidth" className={styles.divider} />
        <Grid container spacing={4} alignItems="center" justifyContent="center" className={styles.musicContainer}>
          {trackList.map((track) => {
            return (
              <Grid item xs={12} sm={6} md={4} key={track.title}>
                <div className={styles.trackContainer}>
                  <SongCard
                    id={track.title.replace(/ /g, "")}
                    songTitle={track.title}
                    albumArtSource={track.artworkSource}
                    externalLink={{ link: track.link, linkType: getLinkType(track) }}
                  />
                </div>
              </Grid>
            );
          })}
        </Grid>
      </main>
    </div>
  );
};

export default Home;
